// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message-deliver/message-deliver.proto

package message_deliver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageReceivedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReceivedRequest) Reset()         { *m = MessageReceivedRequest{} }
func (m *MessageReceivedRequest) String() string { return proto.CompactTextString(m) }
func (*MessageReceivedRequest) ProtoMessage()    {}
func (*MessageReceivedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6cb2e2ba8c5948d, []int{0}
}

func (m *MessageReceivedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReceivedRequest.Unmarshal(m, b)
}
func (m *MessageReceivedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReceivedRequest.Marshal(b, m, deterministic)
}
func (m *MessageReceivedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReceivedRequest.Merge(m, src)
}
func (m *MessageReceivedRequest) XXX_Size() int {
	return xxx_messageInfo_MessageReceivedRequest.Size(m)
}
func (m *MessageReceivedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReceivedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReceivedRequest proto.InternalMessageInfo

type MessageReceivedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReceivedResponse) Reset()         { *m = MessageReceivedResponse{} }
func (m *MessageReceivedResponse) String() string { return proto.CompactTextString(m) }
func (*MessageReceivedResponse) ProtoMessage()    {}
func (*MessageReceivedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6cb2e2ba8c5948d, []int{1}
}

func (m *MessageReceivedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReceivedResponse.Unmarshal(m, b)
}
func (m *MessageReceivedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReceivedResponse.Marshal(b, m, deterministic)
}
func (m *MessageReceivedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReceivedResponse.Merge(m, src)
}
func (m *MessageReceivedResponse) XXX_Size() int {
	return xxx_messageInfo_MessageReceivedResponse.Size(m)
}
func (m *MessageReceivedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReceivedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReceivedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MessageReceivedRequest)(nil), "message_deliver.MessageReceivedRequest")
	proto.RegisterType((*MessageReceivedResponse)(nil), "message_deliver.MessageReceivedResponse")
}

func init() {
	proto.RegisterFile("proto/message-deliver/message-deliver.proto", fileDescriptor_b6cb2e2ba8c5948d)
}

var fileDescriptor_b6cb2e2ba8c5948d = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4d, 0x49, 0xcd, 0xc9, 0x2c, 0x4b,
	0x2d, 0x42, 0xe7, 0xeb, 0x81, 0x55, 0x09, 0xf1, 0x43, 0x85, 0xe3, 0xa1, 0xc2, 0x4a, 0x12, 0x5c,
	0x62, 0xbe, 0x10, 0xa1, 0xa0, 0xd4, 0xe4, 0xd4, 0xcc, 0xb2, 0xd4, 0x94, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x25, 0x49, 0x2e, 0x71, 0x0c, 0x99, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa3,
	0x0a, 0x2e, 0x3e, 0xa8, 0x94, 0x0b, 0xc4, 0x18, 0xa1, 0x34, 0x2e, 0x7e, 0x34, 0xc5, 0x42, 0xea,
	0x7a, 0x68, 0x76, 0xe9, 0x61, 0xb7, 0x48, 0x4a, 0x83, 0xb0, 0x42, 0x88, 0xbd, 0x4a, 0x0c, 0x49,
	0x6c, 0x60, 0x6f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x90, 0xe0, 0xfb, 0xf5, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageDeliverClient is the client API for MessageDeliver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageDeliverClient interface {
	MessageReceived(ctx context.Context, in *MessageReceivedRequest, opts ...grpc.CallOption) (*MessageReceivedResponse, error)
}

type messageDeliverClient struct {
	cc *grpc.ClientConn
}

func NewMessageDeliverClient(cc *grpc.ClientConn) MessageDeliverClient {
	return &messageDeliverClient{cc}
}

func (c *messageDeliverClient) MessageReceived(ctx context.Context, in *MessageReceivedRequest, opts ...grpc.CallOption) (*MessageReceivedResponse, error) {
	out := new(MessageReceivedResponse)
	err := c.cc.Invoke(ctx, "/message_deliver.MessageDeliver/MessageReceived", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageDeliverServer is the server API for MessageDeliver service.
type MessageDeliverServer interface {
	MessageReceived(context.Context, *MessageReceivedRequest) (*MessageReceivedResponse, error)
}

// UnimplementedMessageDeliverServer can be embedded to have forward compatible implementations.
type UnimplementedMessageDeliverServer struct {
}

func (*UnimplementedMessageDeliverServer) MessageReceived(ctx context.Context, req *MessageReceivedRequest) (*MessageReceivedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageReceived not implemented")
}

func RegisterMessageDeliverServer(s *grpc.Server, srv MessageDeliverServer) {
	s.RegisterService(&_MessageDeliver_serviceDesc, srv)
}

func _MessageDeliver_MessageReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReceivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageDeliverServer).MessageReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message_deliver.MessageDeliver/MessageReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageDeliverServer).MessageReceived(ctx, req.(*MessageReceivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageDeliver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message_deliver.MessageDeliver",
	HandlerType: (*MessageDeliverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageReceived",
			Handler:    _MessageDeliver_MessageReceived_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message-deliver/message-deliver.proto",
}
